import { useCallback, useRef, useEffect } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { ask } from '@tauri-apps/plugin-dialog';
import type { DiskVersion, Tab } from '../types';
import { errorService } from '../services/ErrorService';
import {
    readFileContent,
    writeFileContent,
    openFileDialog,
    saveFileDialog,
    addRecentFile,
    rebuildNativeMenu,
    detectEOL,
    analyzeLineEndings,
    type FileWriteResult,
} from '../utils/fileOperations';
import { detectLanguage } from '../utils/languageDetection';
import { fileNameError, suggestedFileName } from '../utils/fileNames';
import { fileWatcher } from '../utils/fileWatcher';
import { LARGE_FILE_WARNING_BYTES, BYTES_PER_MB, MAX_FILE_SIZE_BYTES } from '../constants';
import { notifyDocumentOpened, requestLargeFileView } from '../utils/workspaceViews';
import { startTimer, endTimer } from '../utils/perfMetrics';
import { KeyedTaskQueue } from '../utils/keyedTaskQueue';
import type { TabSaveSnapshot } from './useTabManager';

const baseName = (path: string) => path.split(/[/\\]/).pop() || path;

/** Save errors, with the backend's machine-readable prefixes turned into words. */
function showSaveError(error: unknown): void {
    const message = error instanceof Error ? error.message : String(error);
    if (message.includes('ZITEXT_PARENT_MISSING')) {
        errorService.showError(
            'Folder no longer exists',
            new Error('The folder that contained this file was deleted or renamed. Use Save As to save it somewhere else.'),
        );
        return;
    }
    errorService.showError('Failed to save file', error as Error);
}

/** Language for a document saved under a new path: from the extension, or
 *  the document's current language when the name has no extension. */
function languageForSavedPath(path: string, current: string | undefined): string {
    const detected = detectLanguage(path);
    if (detected === 'plaintext' && !/\.[^.]+$/.test(baseName(path)) && current) return current;
    return detected;
}

/** Tells the backend a document moved, so a `zitext --wait` on it follows. */
function retargetDocument(oldPath: string | null, newPath: string): void {
    if (!oldPath || oldPath === newPath) return;
    void invoke('retarget_document', { oldPath, newPath }).catch(() => { /* bookkeeping only */ });
}

/** Why a background (autosave) write was refused without prompting. */
export type BackgroundSaveBlock = 'conflict' | 'encoding' | 'readonly';

/**
 * Raised instead of showing a dialog when a non-interactive write hits a
 * condition that needs a user decision. Autosave must never open a modal
 * dialog while the user is typing (a reflexive Enter on a pre-selected
 * "Overwrite" button would destroy the external version).
 */
export class BackgroundSaveBlockedError extends Error {
    constructor(readonly reason: BackgroundSaveBlock) {
        super(`Background save blocked: ${reason}`);
        this.name = 'BackgroundSaveBlockedError';
    }
}

interface WriteOptions {
    /** false: never prompt; throw BackgroundSaveBlockedError instead. */
    interactive: boolean;
    /** Overrides the conflict dialog text (e.g. for Revert). */
    conflictMessage?: string;
    conflictOkLabel?: string;
    /** Set once the user agreed to replace a read-only file. */
    allowReadOnly?: boolean;
    /** Called when the user chooses Save Anyway for a read-only file. */
    onReadOnlyAccepted?: () => void;
}

const fileNameOf = (path: string) => path.split(/[/\\]/).pop() || path;

async function writeWithConflictConfirmation(
    path: string,
    content: string,
    encoding: string,
    expectedVersion: DiskVersion | null,
    options: WriteOptions = { interactive: true },
): Promise<FileWriteResult | null> {
    try {
        fileWatcher.beginWrite(path);
        let written: FileWriteResult | undefined;
        try {
            written = await writeFileContent(path, content, encoding, expectedVersion, options.allowReadOnly ?? false);
            return written;
        } finally {
            fileWatcher.endWrite(path, written && {
                modified: written.modified,
                size: written.size,
                exists: true,
                identity: written.identity,
            });
        }
    } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        if (message.includes('ZITEXT_READ_ONLY_FILE:')) {
            if (!options.interactive) throw new BackgroundSaveBlockedError('readonly');
            const saveAnyway = await ask(
                `"${fileNameOf(path)}" is read-only on disk. It may be locked by version control or generated by a tool.\n\n` +
                    'Save your changes anyway? The file stays read-only afterwards.',
                {
                    title: 'Read-Only File',
                    kind: 'warning',
                    okLabel: 'Save Anyway',
                    cancelLabel: 'Cancel',
                },
            );
            if (!saveAnyway) return null;
            options.onReadOnlyAccepted?.();
            return writeWithConflictConfirmation(path, content, encoding, expectedVersion, { ...options, allowReadOnly: true });
        }
        if (message.includes('ZITEXT_ENCODING_UNREPRESENTABLE:')) {
            if (!options.interactive) throw new BackgroundSaveBlockedError('encoding');
            const saveAsUtf8 = await ask(
                'This document contains characters that Windows-1252 cannot represent. Save it as UTF-8 instead?',
                {
                    title: 'Change Encoding?',
                    kind: 'warning',
                    okLabel: 'Save as UTF-8',
                    cancelLabel: 'Cancel',
                },
            );
            if (!saveAsUtf8) return null;
            return writeWithConflictConfirmation(path, content, 'UTF-8', expectedVersion, options);
        }
        if (!message.includes('ZITEXT_FILE_CONFLICT:')) throw error;
        if (!options.interactive) throw new BackgroundSaveBlockedError('conflict');
        const overwrite = await ask(
            options.conflictMessage ??
                `"${fileNameOf(path)}" changed on disk or was removed after it was opened.\n\n` +
                'Overwrite the external version with your current editor content?',
            {
                title: 'File Changed on Disk',
                kind: 'warning',
                okLabel: options.conflictOkLabel ?? 'Overwrite',
                cancelLabel: 'Cancel',
            },
        );
        if (!overwrite) return null;
        return writeWithConflictConfirmation(path, content, encoding, null, options);
    }
}

export interface SaveOptions {
    /** Explicit user save (Ctrl+S, File > Save, save-on-close): advances the
     *  Revert baseline and shows a confirmation toast. */
    manual?: boolean;
    /** Autosave: never prompts. A conflict, a read-only file or an
     *  unrepresentable encoding pauses autosave for the tab until the user
     *  resolves it. */
    background?: boolean;
}

/**
 * useFileManager - Manages file I/O operations
 *
 * Handles opening, saving, and file dialog interactions.
 * Separated from useEditorState for better modularity.
 */
export function useFileManager(
    tabs: Tab[],
    addTab: (tab: Tab) => void,
    updateTab: (tabId: string, updates: Partial<Tab>) => void,
    markTabSaved: (tabId: string, savedRevision: number, updates: Partial<Tab>) => boolean,
    getTabSaveSnapshot: (tabId: string) => TabSaveSnapshot | null,
    findTabIdByPath: (path: string, exceptTabId?: string) => string | undefined,
    setActiveTabId: (id: string) => void,
    markExternallyModified: (tabId: string) => void,
    onRecentFilesChanged?: () => Promise<void> | void
) {
    const openingFiles = useRef(new Map<string, Promise<string | null>>());
    // Read-only files the user chose to save anyway; later saves (including
    // autosave) don't ask again for them.
    const readOnlyAccepted = useRef(new Set<string>());
    // One queue per document for every operation that reads or writes its
    // file (save, Save As, reload, revert), so they can never interleave.
    const saveQueue = useRef(new KeyedTaskQueue());
    // Read through a ref: callers pass a new function each render, and the
    // file actions below must stay stable (the explorer is memoized on them).
    const onRecentFilesChangedRef = useRef(onRecentFilesChanged);
    onRecentFilesChangedRef.current = onRecentFilesChanged;
    const tabsRef = useRef(tabs);
    tabsRef.current = tabs;

    // Tabs whose autosave is paused because a background write needed a user
    // decision (external change, read-only file, or an encoding that can't
    // hold the text).
    // Background saves skip these tabs without touching the disk; any
    // successful manual save, reload or revert resumes autosave.
    const backgroundBlockedRef = useRef(new Map<string, BackgroundSaveBlock>());

    const pauseBackgroundSaves = useCallback((tabId: string, path: string, reason: BackgroundSaveBlock) => {
        if (backgroundBlockedRef.current.has(tabId)) return;
        backgroundBlockedRef.current.set(tabId, reason);
        if (reason === 'conflict') {
            // Surface the persistent "changed on disk" banner for this tab.
            markExternallyModified(tabId);
            errorService.showWarning(
                `Autosave paused for "${fileNameOf(path)}": the file changed on disk. ` +
                'Reload it, or save manually to choose whether to overwrite.',
            );
        } else if (reason === 'readonly') {
            errorService.showWarning(
                `Autosave paused for "${fileNameOf(path)}": the file is read-only on disk. ` +
                'Save manually to choose whether to change it.',
            );
        } else {
            errorService.showWarning(
                `Autosave paused for "${fileNameOf(path)}": the text can't be saved in its current encoding. ` +
                'Save manually to choose UTF-8.',
            );
        }
    }, [markExternallyModified]);

    const resumeBackgroundSaves = useCallback((tabId: string) => {
        backgroundBlockedRef.current.delete(tabId);
    }, []);

    // Per-tab "revert baseline": the content the user last intentionally
    // committed — i.e. the content at open time and after each MANUAL save.
    // Autosave deliberately does NOT update this, so "Revert File" can discard
    // recent edits back to the last real save point even when autosave has
    // already written those edits to disk. (Without this, revert re-read a disk
    // that autosave kept current, so it appeared to do nothing.)
    const revertBaselineRef = useRef(new Map<string, string>());

    useEffect(() => {
        // Drop revert baselines for tabs that no longer exist.
        const tabIds = new Set(tabs.map(t => t.id));
        for (const id of revertBaselineRef.current.keys()) {
            if (!tabIds.has(id)) revertBaselineRef.current.delete(id);
        }
        for (const id of backgroundBlockedRef.current.keys()) {
            if (!tabIds.has(id)) backgroundBlockedRef.current.delete(id);
        }
    }, [tabs]);

    /**
     * Open a file from disk
     */
    const openFileOnce = useCallback(async (
        path: string,
        cursorLine: number = 1,
        cursorColumn: number = 1,
        scrollTop: number = 0,
        scrollLeft: number = 0,
        skipMenuRebuild: boolean = false
    ): Promise<string | null> => {
        try {
            // Check if file is already open BEFORE acquiring the lock so the
            // lock is only held while we're actually reading the file from disk.
            const focusExisting = (tabId: string) => {
                notifyDocumentOpened();
                setActiveTabId(tabId);
                // Apply cursor/scroll if non-default values were requested
                if (cursorLine !== 1 || cursorColumn !== 1 || scrollTop !== 0 || scrollLeft !== 0) {
                    updateTab(tabId, { cursorLine, cursorColumn, scrollTop, scrollLeft });
                }
                return tabId;
            };
            const existingTabId = findTabIdByPath(path);
            if (existingTabId) return focusExisting(existingTabId);

            startTimer('file-open');
            const result = await readFileContent(path);
            // The backend's resolved path: another spelling of an open file
            // (symlink, letter case, relative CLI path) reuses its tab.
            path = result.path || path;
            const openedTabId = findTabIdByPath(path);
            if (openedTabId) return focusExisting(openedTabId);

            // Warn for large files (between the 1 MB warning threshold and the
            // 10 MB hard limit; files above the limit are rejected by the backend
            // before we ever get here).
            if (result.size > LARGE_FILE_WARNING_BYTES) {
                const sizeMB = (result.size / BYTES_PER_MB).toFixed(1);
                const warnMB = (LARGE_FILE_WARNING_BYTES / BYTES_PER_MB).toFixed(0);
                const maxMB = (MAX_FILE_SIZE_BYTES / BYTES_PER_MB).toFixed(0);
                const fileName = path.split(/[/\\]/).pop();
                // Native Tauri dialog rather than window.confirm(), which does not
                // render reliably in a Tauri production webview.
                const proceed = await ask(
                    `File: ${fileName}\n` +
                    `Size: ${sizeMB} MB (larger than the ${warnMB} MB recommended limit)\n\n` +
                    `Files over ${warnMB} MB may open slowly and affect editor performance. ` +
                    `The maximum file size ZITEXT can open is ${maxMB} MB.\n\n` +
                    `Do you want to open it anyway?`,
                    { title: 'Large File Warning', kind: 'warning', okLabel: 'Open', cancelLabel: 'Cancel' }
                );
                if (!proceed) return null;
                // Another open of the same file (other spelling) may have
                // finished while this prompt was up.
                const openedMeanwhile = findTabIdByPath(path);
                if (openedMeanwhile) return focusExisting(openedMeanwhile);
            }

            const language = detectLanguage(path);
            const lineEndings = analyzeLineEndings(result.content);
            const eol = lineEndings.eol;
            if (lineEndings.mixed) {
                errorService.showWarning(
                    `"${baseName(path)}" mixes line-ending styles. ZITEXT keeps one style per document, ` +
                    `so editing and saving it will convert all line endings to ${lineEndings.normalizedTo}.`,
                );
            }

            const newTab: Tab = {
                id: `tab-${Date.now()}-${Math.random()}`,
                path,
                title: path.split(/[/\\]/).pop() || 'Untitled',
                content: result.content,
                revision: 0,
                cursorLine,
                cursorColumn,
                isDirty: false,
                language,
                isReadOnly: false,
                encoding: result.encoding,
                diskVersion: {
                    modified: result.modified,
                    size: result.size,
                    hash: result.hash,
                },
                eol,
                scrollTop,
                scrollLeft,
                isUntitled: false,
                externallyModified: false,
                externalChangeCount: 0,
            };

            endTimer('file-open');
            // The just-read disk content is the initial revert baseline.
            revertBaselineRef.current.set(newTab.id, result.content);
            addTab(newTab);
            notifyDocumentOpened();

            // Start watching file for external changes (cheap, no UI cost).
            fileWatcher.watch(path, newTab.id, () => {
                markExternallyModified(newTab.id);
            });

            // Defer recent-files persistence and the native-menu rebuild until
            // after the document paints. Rebuilding the macOS native menu runs on
            // the main thread (shared with the WebView), so doing it inline holds
            // the just-opened file off screen for a noticeable beat — especially
            // for files opened from the Explorer (which don't skip the rebuild).
            // A macrotask lets the editor render first, then the menu updates.
            setTimeout(async () => {
                try {
                    await addRecentFile(path);
                    if (onRecentFilesChangedRef.current) {
                        await onRecentFilesChangedRef.current();
                    }
                    if (!skipMenuRebuild) {
                        await rebuildNativeMenu();
                    }
                } catch (err) {
                    console.error('[openFile] deferred recent-files/menu update failed:', err);
                }
            }, 0);

            return newTab.id;
        } catch (error) {
            const msg = String(typeof error === 'string' ? error : (error instanceof Error ? error.message : error));
            // Too big for the editor: the Large File viewer reads it from disk
            // a part at a time, read-only. Asked only when someone opened the
            // file just now; batched opens at startup (session restore,
            // launch arguments: skipMenuRebuild) must not wait on a dialog.
            if (msg.includes('File too large') && skipMenuRebuild) {
                const fileName = path.split(/[\\/]/).pop() || path;
                errorService.showWarning(`"${fileName}" is too large to edit. Open it with File → Open Large File or Log… to view it.`);
                return null;
            }
            if (msg.includes('File too large')) {
                const fileName = path.split(/[\\/]/).pop() || path;
                const view = await ask(
                    `"${fileName}" is too large to edit (the editor's limit is ${(MAX_FILE_SIZE_BYTES / BYTES_PER_MB).toFixed(0)} MB).\n\n` +
                    'Open it read-only in the Large File viewer? You can search, filter, follow new lines and export from there.',
                    { title: 'Large File', kind: 'info', okLabel: 'Open in Viewer', cancelLabel: 'Cancel' },
                );
                if (view) requestLargeFileView(path);
                return null;
            }
            // Friendly message for binary/unsupported files instead of a red error
            if (msg.includes('binary') || msg.includes('cannot display') || msg.includes('File too large') || msg.includes('UTF-16')) {
                const fileName = path.split(/[\\/]/).pop() || path;
                errorService.showWarning(`"${fileName}" cannot be opened — ${msg}`);
            } else {
                console.error('[openFile] Error opening file:', path, error);
                errorService.showError('Failed to open file', error as Error);
            }
            return null;
        }
    }, [addTab, findTabIdByPath, setActiveTabId, updateTab, markExternallyModified]);

    // Opens of the same path while one is in progress share its result (the
    // tab id), instead of returning null: a null used to read as "could not
    // open" and released a --wait or created a Recovered tab.
    const openFile = useCallback((
        path: string,
        cursorLine: number = 1,
        cursorColumn: number = 1,
        scrollTop: number = 0,
        scrollLeft: number = 0,
        skipMenuRebuild: boolean = false,
    ): Promise<string | null> => {
        const pending = openingFiles.current.get(path);
        if (pending) return pending;
        const opening = openFileOnce(path, cursorLine, cursorColumn, scrollTop, scrollLeft, skipMenuRebuild)
            .finally(() => openingFiles.current.delete(path));
        openingFiles.current.set(path, opening);
        return opening;
    }, [openFileOnce]);

    /**
     * Open file dialog and load selected file
     */
    const openFileFromDialog = useCallback(async (): Promise<void> => {
        try {
            const path = await openFileDialog();
            // Explicitly check for null or empty string (user cancelled)
            if (path && path.trim() !== '') {
                await openFile(path);
            }
        } catch (error) {
            errorService.showError('Failed to open file', error as Error);
        }
    }, [openFile]);

    /**
     * Save file to disk
     */
    // Returns true only when the file was actually written to disk. Callers that
    // close the tab on save (e.g. the unsaved-changes dialog) MUST check this so
    // a cancelled Save-As or a write error never silently discards the content.
    // `options.manual` marks an explicit user save (Ctrl+S, File > Save,
    // save-on-close). Only manual saves advance the revert baseline; autosave
    // leaves it alone so Revert can still discard back past autosaved edits.
    // `options.background` marks an autosave, which must never prompt.
    /** Save As onto a file that another tab shows would leave two tabs
     *  editing one file; refuse and point to that tab instead. */
    const refuseIfOpenElsewhere = useCallback((savePath: string, tabId: string): boolean => {
        const otherTabId = findTabIdByPath(savePath, tabId);
        if (!otherTabId) return false;
        errorService.showError(
            'File is already open',
            new Error(`"${baseName(savePath)}" is open in another tab. Close that tab first, or choose a different name.`),
        );
        setActiveTabId(otherTabId);
        return true;
    }, [findTabIdByPath, setActiveTabId]);

    const saveFile = useCallback((
        tabId: string,
        contentOverride?: string,
        options: SaveOptions = {},
    ): Promise<boolean> => {
        const isManualSave = options.manual === true;
        const isBackground = options.background === true;
        // A formatter-supplied override is an explicit snapshot, so capture the
        // matching revision now. Ordinary saves intentionally capture both the
        // content and revision only when their queued operation begins.
        const overrideRevision = contentOverride === undefined
            ? undefined
            : getTabSaveSnapshot(tabId)?.revision;

        return saveQueue.current.enqueue(tabId, async (): Promise<boolean> => {
            // The synchronous snapshot (not render-lagged tab state) decides
            // whether the tab still exists: a save queued behind a close must
            // not run for a tab that is gone.
            const initialSnapshot = getTabSaveSnapshot(tabId);
            if (!initialSnapshot) return false;
            if (isBackground && backgroundBlockedRef.current.has(tabId)) return false;

            try {
                let savePath = initialSnapshot.path;
                // Autosave never opens a Save As dialog.
                if (!savePath && isBackground) return false;

            if (!savePath) {
                // Save As for untitled files
                const language = tabsRef.current.find(t => t.id === tabId)?.language ?? 'plaintext';
                savePath = await saveFileDialog(suggestedFileName(initialSnapshot.title, language));
                if (!savePath) return false; // User cancelled
                if (refuseIfOpenElsewhere(savePath, tabId)) return false;
            }

            // Re-read after the (possibly long) Save As dialog: the tab may have
            // been closed meanwhile, in which case nothing is written.
            const snapshot = getTabSaveSnapshot(tabId);
            if (!snapshot) return false;
            const wasUntitled = !snapshot.path;
            // A formatter's output is only saved if nothing changed the
            // document since (a reload or revert queued before this save):
            // otherwise it would write stale text over the current version.
            const useOverride = contentOverride !== undefined && snapshot.revision === overrideRevision;
            const savedContent = useOverride ? contentOverride : snapshot.content;
            const savedRevision = useOverride ? overrideRevision! : snapshot.revision;
            startTimer('file-save');
            const writeResult = await writeWithConflictConfirmation(
                savePath,
                savedContent,
                snapshot.encoding,
                snapshot.path ? snapshot.diskVersion : null,
                {
                    interactive: !isBackground,
                    allowReadOnly: readOnlyAccepted.current.has(savePath),
                    onReadOnlyAccepted: () => readOnlyAccepted.current.add(savePath),
                },
            );
            if (!writeResult) return false;
            endTimer('file-save');
            // Any successful write means the conflict/encoding issue is settled.
            resumeBackgroundSaves(tabId);

            // Update tab with new path and title. An existing file keeps the
            // language mode the user chose; a first save picks one from the name.
            const newTitle = savePath.split(/[/\\]/).pop() || 'Untitled';
            const savedLatestRevision = markTabSaved(tabId, savedRevision, {
                path: savePath,
                title: newTitle,
                ...(wasUntitled
                    ? { language: languageForSavedPath(savePath, tabsRef.current.find(t => t.id === tabId)?.language) }
                    : {}),
                isUntitled: false,
                encoding: writeResult.encoding,
                // What is on disk is now this document's own content.
                externallyModified: false,
                diskVersion: {
                    modified: writeResult.modified,
                    size: writeResult.size,
                    hash: writeResult.hash,
                },
            });

            // Update file watcher:
            // • Untitled files were never watched — start watching now.
            // • Already-watched files — update the stored mod time so the next poll
            //   doesn't fire a false "externally modified" alert.
            if (wasUntitled) {
                // Not for a tab closed while the write was in flight.
                if (getTabSaveSnapshot(tabId)) fileWatcher.watch(savePath, tabId, () => markExternallyModified(tabId));
            } else {
                fileWatcher.updateVersion(savePath, {
                    modified: writeResult.modified,
                    size: writeResult.size,
                    exists: true,
                    identity: writeResult.identity,
                });
            }

            // A manual save is a new "last committed" point for Revert.
            if (isManualSave) {
                revertBaselineRef.current.set(tabId, savedContent);
            }

            await addRecentFile(savePath);
            await onRecentFilesChangedRef.current?.();
            await rebuildNativeMenu();
            // Only announce explicit saves. Autosave runs silently in the
            // background — its "File saved" toast otherwise popped up on every
            // focus change (e.g. when opening the File menu to click Revert).
            if (isManualSave) {
                errorService.showSuccess(`File saved: ${savePath.split(/[\\/]/).pop()}`);
            }
            return savedLatestRevision;
        } catch (error) {
            if (error instanceof BackgroundSaveBlockedError) {
                pauseBackgroundSaves(tabId, initialSnapshot.path ?? initialSnapshot.title, error.reason);
                return false;
            }
            showSaveError(error);
            return false;
        }
        });
    }, [getTabSaveSnapshot, markTabSaved, markExternallyModified, pauseBackgroundSaves, resumeBackgroundSaves, refuseIfOpenElsewhere]);

    /**
     * Save file with new name
     */
    const saveFileAs = useCallback((tabId: string): Promise<void> => {
        return saveQueue.current.enqueue(tabId, async () => {
            const initialSnapshot = getTabSaveSnapshot(tabId);
            if (!initialSnapshot) return;

            try {
            const currentLanguage = tabsRef.current.find(t => t.id === tabId)?.language;
            const defaultName = initialSnapshot.path
                ? baseName(initialSnapshot.path)
                : suggestedFileName(initialSnapshot.title, currentLanguage ?? 'plaintext');
            const savePath = await saveFileDialog(defaultName);
            if (!savePath) return;
            if (refuseIfOpenElsewhere(savePath, tabId)) return;

            const snapshot = getTabSaveSnapshot(tabId);
            if (!snapshot) return;
            const writeResult = await writeWithConflictConfirmation(
                savePath,
                snapshot.content,
                snapshot.encoding,
                savePath === snapshot.path ? snapshot.diskVersion : null,
            );
            if (!writeResult) return;
            resumeBackgroundSaves(tabId);

            // Update tab with new path and title
            const newTitle = savePath.split(/[/\\]/).pop() || 'Untitled';
            markTabSaved(tabId, snapshot.revision, {
                path: savePath,
                title: newTitle,
                language: savePath === snapshot.path
                    ? currentLanguage ?? detectLanguage(savePath)
                    : languageForSavedPath(savePath, currentLanguage),
                isUntitled: false,
                encoding: writeResult.encoding,
                // What is on disk is now this document's own content.
                externallyModified: false,
                diskVersion: {
                    modified: writeResult.modified,
                    size: writeResult.size,
                    hash: writeResult.hash,
                },
            });

            // Save As is always an explicit save — reset the revert baseline.
            revertBaselineRef.current.set(tabId, snapshot.content);

            // Unwatch the old path (if any) and start watching the new path.
            if (snapshot.path !== savePath) {
                if (snapshot.path) fileWatcher.unwatch(snapshot.path, tabId);
                // Not for a tab closed while the write was in flight.
                if (getTabSaveSnapshot(tabId)) fileWatcher.watch(savePath, tabId, () => markExternallyModified(tabId));
                retargetDocument(snapshot.path, savePath);
            } else {
                fileWatcher.updateVersion(savePath, {
                    modified: writeResult.modified,
                    size: writeResult.size,
                    exists: true,
                    identity: writeResult.identity,
                });
            }

            await addRecentFile(savePath);
            await onRecentFilesChangedRef.current?.();
            await rebuildNativeMenu();
            errorService.showSuccess(`File saved as: ${savePath.split(/[\\/]/).pop()}`);
            } catch (error) {
                showSaveError(error);
            }
        });
    }, [getTabSaveSnapshot, markTabSaved, markExternallyModified, resumeBackgroundSaves, refuseIfOpenElsewhere]);

    /**
     * Reload a tab from disk without queueing. Only call this from a task that
     * is already running on the tab's queue (reloadFileFromDisk, or the
     * revert fallback); enqueueing again from inside a task would deadlock.
     */
    const reloadNow = useCallback(async (tabId: string, skipDirtyConfirm: boolean): Promise<boolean> => {
        const tab = tabsRef.current.find(t => t.id === tabId);
        const snapshot = getTabSaveSnapshot(tabId);
        if (!tab || !snapshot || !snapshot.path) return false;
        const path = snapshot.path;

        if (tab.isDirty && !skipDirtyConfirm) {
            const confirmed = await ask(
                `Reloading "${tab.title}" will discard your unsaved changes. Continue?`,
                {
                    title: 'Discard Unsaved Changes?',
                    kind: 'warning',
                    okLabel: 'Reload',
                    cancelLabel: 'Cancel',
                },
            );
            if (!confirmed) return false;
        }

        // The user agreed to discard the buffer as it is now. Edits typed while
        // the file is being read are newer than that decision, so the read
        // result is applied only if the buffer is still at this revision.
        const decided = getTabSaveSnapshot(tabId);
        if (!decided || decided.path !== path) return false;

        const result = await readFileContent(path);

        const current = getTabSaveSnapshot(tabId);
        if (!current) return false;
        if (current.revision !== decided.revision || current.path !== path) {
            errorService.showWarning(
                `Reload of "${fileNameOf(path)}" was cancelled because the document changed while it was being read. ` +
                'Reload again to discard those edits.',
            );
            return false;
        }

        updateTab(tabId, {
            content: result.content,
            eol: detectEOL(result.content),
            encoding: result.encoding,
            diskVersion: {
                modified: result.modified,
                size: result.size,
                hash: result.hash,
            },
            isDirty: false,
            externallyModified: false,
        });

        // Update file watcher with new mod time
        fileWatcher.updateVersion(path, {
            modified: result.modified,
            size: result.size,
            exists: true,
            identity: result.identity,
        });
        // Reloading from disk accepts the on-disk content as the new
        // baseline (this path is the external-change "Reload" action).
        revertBaselineRef.current.set(tabId, result.content);
        resumeBackgroundSaves(tabId);
        return true;
    }, [getTabSaveSnapshot, updateTab, resumeBackgroundSaves]);

    /**
     * Reload file from disk (after external modification).
     * Returns whether the reload actually happened — false means the tab/path
     * was missing, the user backed out of the dirty-discard confirmation, or
     * the document was edited while the file was being read.
     * Runs on the tab's queue so it never interleaves with a save or revert.
     */
    const reloadFileFromDisk = useCallback((tabId: string, skipDirtyConfirm = false): Promise<boolean> => {
        return saveQueue.current.enqueue(tabId, () => reloadNow(tabId, skipDirtyConfirm));
    }, [reloadNow]);

    /**
     * Revert File: discard edits made since the last intentional save, back to
     * the tab's revert baseline (content at open / last manual save). Unlike
     * reloadFileFromDisk this does NOT re-read the current disk — autosave may
     * have written the very edits we want to drop — and it writes the baseline
     * back to disk so those autosaved edits are actually undone in the file.
     *
     * The write still carries the expected disk version: if another program
     * changed or removed the file, the user must explicitly agree before
     * Revert replaces that newer version. Runs on the tab's queue, so pending
     * saves finish first and later ones see the reverted state.
     * Returns true if it reverted, false if cancelled or nothing to revert.
     */
    const revertToBaseline = useCallback((tabId: string): Promise<boolean> => {
        return saveQueue.current.enqueue(tabId, async (): Promise<boolean> => {
            const snapshot = getTabSaveSnapshot(tabId);
            if (!snapshot || !snapshot.path) return false;
            const path = snapshot.path;

            const baseline = revertBaselineRef.current.get(tabId);
            if (baseline === undefined) {
                // No baseline captured (shouldn't happen for a saved file) — fall
                // back to a plain disk reload so the menu action still does something.
                return reloadNow(tabId, true);
            }

            const writeResult = await writeWithConflictConfirmation(
                path,
                baseline,
                snapshot.encoding,
                snapshot.diskVersion,
                {
                    interactive: true,
                    conflictMessage:
                        `"${fileNameOf(path)}" changed on disk or was removed after it was last saved in ZITEXT.\n\n` +
                        'Reverting will replace that newer version with your last saved content. Revert anyway?',
                    conflictOkLabel: 'Revert Anyway',
                },
            );
            if (!writeResult) return false;
            resumeBackgroundSaves(tabId);

            const diskVersion = {
                modified: writeResult.modified,
                size: writeResult.size,
                hash: writeResult.hash,
            };
            fileWatcher.updateVersion(path, {
                modified: writeResult.modified,
                size: writeResult.size,
                exists: true,
                identity: writeResult.identity,
            });

            const current = getTabSaveSnapshot(tabId);
            if (!current) return true;
            if (current.revision !== snapshot.revision) {
                // Edits typed while the revert was being written are newer than
                // the user's decision: keep them, unsaved, over the reverted file.
                updateTab(tabId, { encoding: writeResult.encoding, diskVersion, externallyModified: false });
                errorService.showWarning(
                    `"${fileNameOf(path)}" was reverted on disk. Edits made during the revert were kept and are unsaved.`,
                );
                return true;
            }

            updateTab(tabId, {
                content: baseline,
                eol: detectEOL(baseline),
                encoding: writeResult.encoding,
                diskVersion,
                isDirty: false,
                externallyModified: false,
            });
            return true;
        });
    }, [getTabSaveSnapshot, reloadNow, updateTab, resumeBackgroundSaves]);

    /**
     * Rename a file on disk and update the tab. Runs on the document's queue,
     * so a save in flight can't write the old path back afterwards.
     */
    const renameFile = useCallback((tabId: string, requestedName: string): Promise<void> => {
        return saveQueue.current.enqueue(tabId, async () => {
            const snapshot = getTabSaveSnapshot(tabId);
            if (!snapshot) return;
            const newName = requestedName.trim();
            const currentName = snapshot.path ? baseName(snapshot.path) : snapshot.title;
            if (newName === currentName) return;
            const problem = fileNameError(newName);
            if (problem) {
                errorService.showError('Invalid file name', new Error(problem));
                return;
            }

            try {
                if (!snapshot.path) {
                    // For untitled files, just update the title
                    updateTab(tabId, { title: newName });
                    return;
                }

                const oldPath = snapshot.path;
                const pathParts = oldPath.split(/[\\/]/);
                pathParts.pop();
                const newPath = [...pathParts, newName].join(oldPath.includes('\\') ? '\\' : '/');
                const sameFile = newPath.toLowerCase() === oldPath.toLowerCase();
                if (!sameFile && findTabIdByPath(newPath, tabId)) {
                    errorService.showError('Failed to rename file', new Error(`"${newName}" is already open in another tab.`));
                    return;
                }

                const renamed = await invoke<boolean>('rename_file', { oldPath, newPath });
                if (renamed === false) return; // cancelled in the confirmation dialog

                fileWatcher.unwatch(oldPath, tabId);
                // Not for a tab closed while the rename was being confirmed.
                if (getTabSaveSnapshot(tabId)) {
                    fileWatcher.watch(newPath, tabId, () => {
                        markExternallyModified(tabId);
                    });
                }

                const language = tabsRef.current.find(t => t.id === tabId)?.language;
                updateTab(tabId, {
                    path: newPath,
                    title: newName,
                    language: languageForSavedPath(newPath, language),
                });

                await addRecentFile(newPath);
                await onRecentFilesChangedRef.current?.();
                await rebuildNativeMenu();
                errorService.showSuccess(`Renamed to ${newName}`);
            } catch (error) {
                errorService.showError('Failed to rename file', error as Error);
            }
        });
    }, [getTabSaveSnapshot, findTabIdByPath, updateTab, markExternallyModified]);

    return {
        openFile,
        openFileFromDialog,
        saveFile,
        saveFileAs,
        reloadFileFromDisk,
        revertToBaseline,
        renameFile,
    };
}
